### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by francescovenica** [marklawlor/react-window-timeline#10]
Hello,

I'm trying to replicate the interactive example on a fresh nextjs app but I'm getting this error when importing:

```
import interact from "@interactjs/interact";
import "@interactjs/auto-start";
import "@interactjs/auto-scroll";
import "@interactjs/actions/drag";
import "@interactjs/actions/resize";
import "@interactjs/modifiers";
```

this is the package
```
    "@interactjs/actions": "1.10.3",
    "@interactjs/auto-scroll": "1.10.3",
    "@interactjs/auto-start": "1.10.3",
    "@interactjs/interact": "1.10.3",
    "@interactjs/modifiers": "1.10.3",
    "@interactjs/types": "^1.10.3",
    "@interactjs/utils": "1.10.3",
```

any idea why?
many thanks

**Comment by francescovenica** [comment]
ok, I've fixed it using react-dnd, if can be useful I can upload an example

**Comment by marklawlor** [comment]
@francescovenica You can only use `import` statements while inside an ECMAScript module (also known as ESM). If you are not using ESM then you need to use a transpiler to convert it to commonjs. It appears you are not transpiling and trying to use `import` outside of a esm module.

The example works because it was written in Typescript and is using the Typescript compiler to convert to `commonjs`. 

I would recommend reading the [Node docs on ESM](https://nodejs.org/api/esm.html) or the [mdn docs on Javascript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)
